# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do
    setup_circle_ci
  end
  
  desc "Runs all the tests"
  lane :test do
    print "Fastlane works successfully"
  end

  desc "Prepare Android Debug Build"
  lane :build_debug_android do
    gradle(
      task: "assembleDebug",
    )
  end

  desc "Prepare Android Release Build"
  lane :build_release_android do
    gradle(
      task: "assembleRelease",
    )
  end

  desc "increment version code for android build"
  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:742795928529:android:c7a58cc62380fcfd3936f0"
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  end

  desc "Prepare Android Build & Distribute to Firebase App distribution"
  lane :deploy_apk_to_firebase_android do 
    increment_version
    build_release_android
    firebase_app_distribution(
      app: "1:742795928529:android:c7a58cc62380fcfd3936f0",
      firebase_cli_token: "1//03bgve6KRkTdICgYIARAAGAMSNwF-L9IrnARPyhzIGci_3zUegIRghbVagZeLisoNv9xT_8MEsYPWQIbFz21G9S6nbYjiUIWw5zw",
      groups: "payment_testers",
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/apk/release/app-release.apk",
    )
  end
end